#!/usr/bin/env bash
# Collect ncu (Nsight Compute) and nsys (Nsight Systems) profiles for the
# LambdaGPUPipeline<32ch/4fpga> configuration, then generate figures.
#
# Usage:
#   ./benchmarking/run_profile.sh [--output-dir DIR] [--iterations N]
#                                 [--ncu-only] [--nsys-only] [--skip-plots]
#
# Outputs (in OUTPUT_DIR):
#   ncu_metrics.csv   — per-kernel metrics CSV (parse with plot_profiles.py)
#   ncu_report.ncu-rep — binary ncu report (open in Nsight Compute GUI)
#   nsys_profile.nsys-rep — binary nsys timeline (open in Nsight Systems GUI)
#   *.png             — figures generated by plot_profiles.py
#
# Prerequisites:
#   ncu   (Nsight Compute CLI, usually at /usr/local/cuda/bin/ncu or in $PATH)
#   nsys  (Nsight Systems CLI, usually at /usr/local/cuda/bin/nsys or in $PATH)
#   bench_gpu_profile binary built in $BUILD_DIR/apps/
#
# Environment (same as run_benchmarks.sh — set in apptainer.def %environment):
#   CUDA_HOME=/opt/conda/targets/x86_64-linux  (for NVRTC JIT includes)
#   LD_LIBRARY_PATH=/opt/conda/lib:...

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$REPO_ROOT/build"

ITERATIONS=5       # profiling iterations (after warmup); 3-5 is enough for ncu
WARMUP=2           # warmup iterations to flush TCC NVRTC JIT before profiling
OUTPUT_DIR="$SCRIPT_DIR/$(date +%Y%m%d_%H%M%S)_profile"
RUN_NCU=true
RUN_NSYS=true
SKIP_PLOTS=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)  OUTPUT_DIR="$2"; shift 2 ;;
    --iterations)  ITERATIONS="$2"; shift 2 ;;
    --ncu-only)    RUN_NSYS=false; shift ;;
    --nsys-only)   RUN_NCU=false; shift ;;
    --skip-plots)  SKIP_PLOTS=true; shift ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "Profiling iterations: $ITERATIONS  (warmup: $WARMUP)"

export CUDA_HOME=/opt/conda/targets/x86_64-linux
export LD_LIBRARY_PATH="/opt/conda/lib:/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# /tmp is full on this system (250 MB, 100% used).
# nsys rejects tmpfs (/dev/shm) for its CUDA config file — use Lustre for it.
# ncu does kernel-replay I/O so we put it on /dev/shm (479 GB RAM-backed tmpfs).
FRED=/fred/oz002/jsmallwo
if [[ -w /dev/shm ]]; then
  NCU_TMPDIR=$(mktemp -d /dev/shm/ncu_XXXXXX)
elif [[ -w $FRED ]]; then
  NCU_TMPDIR=$(mktemp -d "$FRED/ncu_XXXXXX")
else
  echo "ERROR: no writable temp space for ncu (tried /dev/shm, $FRED)" >&2; exit 1
fi
if [[ -w $FRED ]]; then
  NSYS_TMPDIR=$(mktemp -d "$FRED/nsys_XXXXXX")
elif [[ -w /dev/shm ]]; then
  NSYS_TMPDIR=$(mktemp -d /dev/shm/nsys_XXXXXX)
else
  echo "ERROR: no writable temp space for nsys (tried $FRED, /dev/shm)" >&2; exit 1
fi
trap 'rm -rf "$NCU_TMPDIR" "$NSYS_TMPDIR"' EXIT
echo "ncu  temp dir: $NCU_TMPDIR"
echo "nsys temp dir: $NSYS_TMPDIR"

# /tmp is a 250 MB partition that fills up with stale nsight-compute-* dirs from
# prior ncu runs.  Clear them so nsys can write its CUDA injection config file.
echo "Clearing stale ncu leftovers from /tmp..."
rm -rf /tmp/nsight-compute-* /tmp/nvidia 2>/dev/null || true

BINARY="$BUILD_DIR/apps/bench_gpu_profile"

if [[ ! -x "$BINARY" ]]; then
  echo "ERROR: binary not found or not executable: $BINARY" >&2
  echo "       Run cmake --build build from the repo root first." >&2
  exit 1
fi

# Prefer ncu/nsys from CUDA toolkit; fall back to PATH
NCU="${CUDA_HOME}/../../bin/ncu"
NSYS="${CUDA_HOME}/../../bin/nsys"
[[ -x "$NCU"  ]] || NCU=ncu
[[ -x "$NSYS" ]] || NSYS=nsys

echo "Git commit: $(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
echo "Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo

# ---------------------------------------------------------------------------
# nsys: timeline profile
# Captures CUDA API + kernel launches + NVTX for the full pipeline execution.
# Open nsys_profile.nsys-rep in the Nsight Systems GUI for the timeline view.
# ---------------------------------------------------------------------------
if $RUN_NSYS; then
  echo "=== nsys: timeline profile ==="
  NSYS_REPORT="$OUTPUT_DIR/nsys_profile"

  # nsys does not need replays — one pass captures the full timeline.
  # Use --iterations 10 for a longer capture so each pipeline stage is clearly
  # visible across multiple invocations in the timeline.
  TMPDIR="$NSYS_TMPDIR" "$NSYS" profile \
    --trace=cuda,nvtx,cudnn,cublas \
    --output="$NSYS_REPORT" \
    --force-overwrite=true \
    --stats=true \
    "$BINARY" \
      --iterations 10 \
      --warmup "$WARMUP" \
    2>&1 | tee "$OUTPUT_DIR/nsys_stdout.txt"

  echo "nsys report: ${NSYS_REPORT}.nsys-rep"
  echo
fi

# ---------------------------------------------------------------------------
# ncu: per-kernel metrics
#
# Sections collected:
#   SpeedOfLight          — SM + DRAM throughput as % of peak; kernel duration
#   Occupancy             — achieved vs theoretical warp occupancy
#   MemoryWorkloadAnalysis_Chart — L1/L2/DRAM bandwidth breakdown
#   WarpStateStats         — per-kernel stall-reason breakdown (bottleneck analysis)
#
# Extra --metrics (not covered by the sections above):
#   sm__pipe_tensor_cycles_active...pct_of_peak_sustained_elapsed
#     Overall tensor-core pipe duty cycle as % of sustained peak.
#   sm__pipe_tensor_op_{hmma,imma}_cycles_active_v2...pct_of_peak_sustained_elapsed
#     Tensor-pipe duty cycle split by precision -- HMMA = fp16/bf16, IMMA =
#     int8/int4/binary.  The overall tensor-pipe figure is precision-agnostic,
#     so these counters show whether a tensor-heavy kernel (e.g. `correlate`,
#     `wmma_complex_gemm_opt`) is actually running fp16/bf16 or integer tensor
#     ops.
#   smsp__average_warps_issue_stalled_<reason>_per_issue_active.pct
#     Per-kernel breakdown of *why* warps weren't issuing (barrier wait,
#     memory scoreboard, throttling, etc.), expressed as % of total stall
#     cycles -- this is what actually identifies the bottleneck for a kernel
#     with low achieved occupancy/SM throughput (e.g. `correlate`).
#
# --replay-mode application:
#   Re-runs the entire binary once per metric collection pass.  This is
#   required to correctly profile kernels inside CUDA graphs (LambdaGPUPipeline
#   captures pre-eigen and post-eigen sequences as graphs).  kernel-replay mode
#   would only see the graph boundary launch, not the individual nodes.
#
# The CSV is written to ncu_metrics.csv; the binary report to ncu_report.ncu-rep
# (open in Nsight Compute GUI for the full interactive roofline / source view).
# ---------------------------------------------------------------------------
if $RUN_NCU; then
  echo "=== ncu: per-kernel metrics ==="
  NCU_CSV="$OUTPUT_DIR/ncu_metrics.csv"
  NCU_REPORT="$OUTPUT_DIR/ncu_report"

  STALL_REASONS=(
    barrier branch_resolving dispatch_stall drain imc_miss lg_throttle
    long_scoreboard math_pipe_throttle membar mio_throttle misc
    no_instruction not_selected short_scoreboard sleeping tex_throttle wait
  )
  STALL_METRICS=""
  for reason in "${STALL_REASONS[@]}"; do
    STALL_METRICS+="smsp__average_warps_issue_stalled_${reason}_per_issue_active.pct,"
  done

  TENSOR_METRICS=(
    sm__pipe_tensor_cycles_active.avg.pct_of_peak_sustained_elapsed
    sm__pipe_tensor_cycles_active.max.pct_of_peak_sustained_elapsed
    sm__pipe_tensor_cycles_active.min.pct_of_peak_sustained_elapsed
    sm__pipe_tensor_cycles_active.sum.pct_of_peak_sustained_elapsed
    sm__pipe_tensor_op_hmma_cycles_active_v2.avg.pct_of_peak_sustained_elapsed
    sm__pipe_tensor_op_imma_cycles_active_v2.avg.pct_of_peak_sustained_elapsed
  )
  TENSOR_METRICS_CSV="$(IFS=,; echo "${TENSOR_METRICS[*]}")"

  # ncu writes its own preamble lines beginning with "==" to stdout before
  # the CSV header; redirect stderr separately so they don't corrupt the CSV.
  TMPDIR="$NCU_TMPDIR" "$NCU" \
    --section SpeedOfLight \
    --section Occupancy \
    --section MemoryWorkloadAnalysis_Chart \
    --section WarpStateStats \
    --metrics "${STALL_METRICS}${TENSOR_METRICS_CSV}" \
    --replay-mode application \
    --target-processes all \
    --export "$NCU_REPORT" \
    --force-overwrite \
    --csv \
    "$BINARY" \
      --iterations "$ITERATIONS" \
      --warmup "$WARMUP" \
    > "$NCU_CSV" \
    2> "$OUTPUT_DIR/ncu_stderr.txt"

  echo "ncu CSV:    $NCU_CSV"
  echo "ncu report: ${NCU_REPORT}.ncu-rep"
  echo
fi

# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
if ! $SKIP_PLOTS && [[ -f "$OUTPUT_DIR/ncu_metrics.csv" ]]; then
  PLOT_SCRIPT="$SCRIPT_DIR/plot_profiles.py"
  if [[ -f "$PLOT_SCRIPT" ]]; then
    echo "Generating figures..."
    PYTHON="${PYTHON:-python3}"
    if "$PYTHON" "$PLOT_SCRIPT" --results-dir "$OUTPUT_DIR"; then
      echo "Figures saved to $OUTPUT_DIR"
    else
      echo "Plotting failed — ncu CSV is still in $OUTPUT_DIR" >&2
    fi
  else
    echo "plot_profiles.py not found — skipping figures"
  fi
fi

echo "Done: $OUTPUT_DIR"
